apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  labels:
    app: frontend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: europe-docker.pkg.dev/cloud-computing-project-372323/eu.gcr.io/frontend:latest
        ports:
        - containerPort: 80
        imagePullPolicy: Always