apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: frontendserver
  name: frontendserver
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: frontendserver
  type: LoadBalancer
status:
  loadBalancer: {}